version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-blog-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: celery_worker.Dockerfile
    container_name: fastapi-blog-celery
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: fastapi-blog-redis
    ports:
      - "6379:6379"
